# permissions for end users to view rcsconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: rcsconfig-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: rcs-ocm-deployer
    app.kubernetes.io/part-of: rcs-ocm-deployer
    app.kubernetes.io/managed-by: kustomize
  name: rcsconfig-viewer-role
rules:
- apiGroups:
  - rcsd.dana.io
  resources:
  - rcsconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rcsd.dana.io
  resources:
  - rcsconfigs/status
  verbs:
  - get
